### PR TITLE
218: Swipe left/right on product images to navigate between images

### PR DESCRIPTION
**Pull request by MiteshiOS**
## Task

- [218: Swipe left/right on product images to navigate between images](https://trello.com/c/BGBSS6v8/218-swipe-left-right-on-product-images-to-navigate-between-images)

## Description & Notes

- Removed PhotoSelectionCell from ProductDetailsVC
- Added CollectionView in ProductTopCell

## Visuals

https://user-images.githubusercontent.com/17427703/179346384-4abae734-33f7-407a-97d0-a25fd829add6.mp4

### CODE REVIEW

**Review by tejen — CHANGES_REQUESTED** [review]
🐞 We'll need to keep PhotoSelectionCell in order to match the mocks. I've added a link to the mocks for this VC into the Trello card for this PR. @MiteshiOS

**Review by tejen — CHANGES_REQUESTED** [review]
@MiteshiOS it looks like the original CollectionView of thumbnails has been deleted. **Let's add the CollectionView of thumbnails back into the app.** We need to keep that CollectionView to match the mocks, so the user can scroll through thumbnails. See screenshot below...

Screen Shot 2022-07-20 at 11 41 57 AM

**Comment by MiteshiOS** [comment]
> @MiteshiOS it looks like the original CollectionView of thumbnails has been deleted. **Let's add the CollectionView of thumbnails back into the app.** We need to keep that CollectionView to match the mocks, so the user can scroll through thumbnails. See screenshot below...
> 
> Screen Shot 2022-07-20 at 11 41 57 AM

**Comment by MiteshiOS** [comment]
Yes @tejen As I show you the results in the meeting. Actually, I didn't push that update to match my existing changes with the Figma mock-up. I will add updates into this PR soon.

**Comment by MiteshiOS** [comment]
@tejen Please take a look. I added the collectionview thumbnail again.

https://user-images.githubusercontent.com/17427703/180465261-de379c58-f6b3-4780-8dbc-903d97f6bf79.mp4

**Comment by tejen** [comment]
Thanks @MiteshiOS. Got a crash below while scrolling through the top image:

https://user-images.githubusercontent.com/1665102/180468616-f5cd9812-2e51-4ccd-b736-93a60fe1a44c.mp4

**Review by tejen — APPROVED** [review]

**Pull request merged**
